"use client";

import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { SETTINGS_DEFAULTS } from "@/lib/mock-data";
import { Bell, Shield, Trash2, Zap } from "lucide-react";
import { useState } from "react";

function Section({ title, icon: Icon, children, danger = false }: { title: string; icon: typeof Zap; children: React.ReactNode; danger?: boolean }) { return <Card className={danger ? "border-jp-rose/35" : ""}><div className="mb-1 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-[0.12em] text-jp-text-dim"><Icon size={12} />{title}</div>{children}</Card>; }
function Row({ label, description, children }: { label: string; description?: string; children: React.ReactNode }) { return <div className="flex items-center justify-between border-b border-jp-border py-3.5 last:border-0"><div className="pr-4"><div className="text-sm text-jp-paper">{label}</div>{description && <div className="mt-0.5 text-xs text-jp-text-dim2">{description}</div>}</div>{children}</div>; }

export default function SettingsPage() {
  const [settings, setSettings] = useState(SETTINGS_DEFAULTS);
  return <div className="max-w-2xl space-y-5 px-6 py-6"><Section title="Automation" icon={Zap}><Row label="Auto-tailor resume on new application" description="AI drafts a tailored version immediately; still requires your approval"><Switch aria-label="Auto-tailor resume" checked={settings.autoTailor} onCheckedChange={(autoTailor) => setSettings({ ...settings, autoTailor })} /></Row><Row label="Follow-up reminder delay" description="Days to wait before drafting a follow-up email"><div className="flex items-center gap-2"><Input type="number" min={1} className="w-14 text-center font-mono" value={settings.followupDays} onChange={(event) => setSettings({ ...settings, followupDays: Number(event.target.value) })} /><span className="text-xs text-jp-text-dim2">days</span></div></Row><Row label="Dark interface" description="JobPilot is designed dark-first"><Switch aria-label="Dark interface" checked={settings.darkMode} onCheckedChange={(darkMode) => setSettings({ ...settings, darkMode })} /></Row></Section><Section title="Notifications" icon={Bell}><Row label="Email notifications" description="Status changes, follow-up drafts ready, weekly summary"><Switch aria-label="Email notifications" checked={settings.emailNotifications} onCheckedChange={(emailNotifications) => setSettings({ ...settings, emailNotifications })} /></Row><Row label="Notification email"><span className="font-mono text-xs text-jp-text-dim">sushanto@mail.com</span></Row></Section><Section title="Account" icon={Shield}><Row label="Plan" description="Free — 20 applications / month"><button type="button" className="rounded-md bg-jp-amber px-3 py-1.5 text-xs font-semibold text-jp-base">Upgrade</button></Row><Row label="Export my data" description="Download all applications, resumes, and events as JSON"><button type="button" className="rounded-md border border-jp-border px-3 py-1.5 text-xs text-jp-paper">Export</button></Row></Section><Section title="Danger zone" icon={Trash2} danger><Row label="Delete account" description="Permanently removes all applications, resumes, and history"><button type="button" className="flex items-center gap-1.5 rounded-md border border-jp-rose/35 bg-jp-rose/10 px-3 py-1.5 text-xs text-jp-rose"><Trash2 size={12} /> Delete</button></Row></Section></div>;
}
